name: ci

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v4
      - run: ./build.sh
#      - run: ./smoke_test.sh
