name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 23.0.1
      - uses: actions/checkout@v2
      - run: ./build.sh
      - run: ./smoke_test.sh
